### ISSUE TITLE
[FR] Full Frame Pop-up Toggle

### ISSUE THREAD

**Issue by brownts** [karthink/popper#12] opened 2021-09-11 14:10 UTC
Thanks for creating Popper!

I did use Popwin briefly, for one specific feature, that never really worked correctly for me.  The "one window" capability in Popwin allowed you to maximize a pop-up and subsequently restore the previous window configuration when you were done.  This was useful for pop-ups where you might want to briefly jump to a full frame (such as a compilation buffer or shell). I never did get the restoration back down to work properly for compilation buffers though.

It would be nice if something like this were easy to do (i.e., low friction :smile:) with Popper.  The fact that the pop-ups are considered side windows means you cannot <kbd>C-x 1</kbd> to maximize the window.  Thus, it appears you must first raise the window and then perform <kbd>C-x 1</kbd>.  Furthermore, to restore the window layout, you need something like `winner-undo` (since Emacs won't let you make a side window from the only window in a frame) and then lower the window back down.

This last limitation (where you can't create a side-window from the only window on a frame), may be triggering a minor bug in Popper.  I noticed when I try to do this, I get the Emacs "Attempt to delete minibuffer or sole ordinary window" error message.  I think Popper gets confused (and out-of-sync with the actual window arrangement), since when I perform a `winner-undo` to go back to a multi-window frame, the modeline will now contain "POP".  If I subsequently attempt to lower the window, nothing happens...except that "POP" is removed from the modeline.  Attempting to lower the window again will then put the window in the side-window.  Therefore, it might be necessary for Popper to have some logic about attempting to lower the only window in a frame to prevent getting out-of-sync like this, at least when `popper-display-control` is enabled.

**Comment by karthink** [comment] 2021-09-11 18:32
> Popwin allowed you to maximize a pop-up and subsequently restore the previous window configuration when you were done

Popper doesn't currently do this (except through raising + C-x 1), but I do this all the time with windows, including side windows using the following:

```elisp
  (defvar my/window-configuration nil
    "Current window configuration.
Intended for use by `my/window-single-toggle'.")

  (define-minor-mode my/monocle-mode
    "Toggle between multiple windows and single window.
This is equivalent to maximising a window."
    :lighter " [M]"
    :global nil
    (let ((win my/window-configuration))
      (if (one-window-p)
          (when win
            (set-window-configuration win))
        (setq my/window-configuration (current-window-configuration))
        (when (window-parameter nil 'window-slot)
            (let ((buf (current-buffer)))
              (other-window 1)
              (switch-to-buffer buf)))
        (delete-other-windows)))))

```

I bind `my/monocle-mode` to a key. I use it with Popper without any issues.

> It would be nice if something like this were easy to do (i.e., low friction) with Popper.

I'll think about adding a `popper-maximize-popup` command. The problem with this (and with `my/monocle-mode`) from above is that if you change your window configuration through any action that isn't calling the same command again, the stored window configuration is now stale. This causes unexpected behavior in the future. Let me investigate how popwin does this.

> I noticed when I try to do this, I get the Emacs "Attempt to delete minibuffer or sole ordinary window" error message.

Can you provide steps to reproduce this? It's not clear what "this" is in "try to do this".

**Comment by brownts** [comment] 2021-09-11 22:46
> I bind `my/monocle-mode` to a key. I use it with Popper without any issues.
> 

Ah, nice example there.  Open the buffer in a different non-side window and then make that window the only window in the frame.  Neat idea.  I think I can adapt this for my use.  I understand what you're saying about it being somewhat brittle, depending on whether the window configuration changes before you restore it.

> > I noticed when I try to do this, I get the Emacs "Attempt to delete minibuffer or sole ordinary window" error message.
> 
> Can you provide steps to reproduce this? It's not clear what "this" is in "try to do this".

This might just be me not understanding how this would work, but seemed odd to me.  I'm using the default `popper-display-control` and `popper-display-function` settings, so that Popper should place the pop-up in the side-window at the bottom of the frame. 
1. Start with 2 windows open in the frame (just to have something for `winner-undo` to come back to).
2. <kbd>C-x 1</kbd> to only have 1 window in the frame.
3. <kbd>C-M-`</kbd> to attempt to lower the only window.  Emacs generates the error message noted above.
4. <kbd>M-x winner-undo</kbd> to get back to the 2 window configuration.  This is where the window we attempted to lower earlier now has "POP" in the modeline, but is not shown as a pop-up window (i.e., not in the side-window at the bottom of the frame).
5. <kbd>C-M-`</kbd> again to attempt to lower the window again (now that we are in the 2 window configuration).  This doesn't lower the window, but does remove "POP" from the modeline.
6. <kbd>C-M-`</kbd> a 3rd time...this time the window does move to the pop-up at the bottom.

Maybe this is just an artifact of using `winner-undo` to restore a previous window configuration and now it's not really in-sync anymore, but it would seem that Popper believes this is a pop-up window even though the original Emacs error occurred and the window was never placed in the side window.  I was thinking that if Emacs didn't allow you to convert the window to a side window, that Popper should not consider it to be a pop-up window (at least with `popper-display-control` and `popper-display-function` at their default settings).

**Comment by karthink** [comment] 2021-09-12 00:10
I wasn't able to reproduce this until I installed Popper from MELPA. Turns out this was fixed in a recent commit but MELPA hasn't updated it yet. For some reason the MELPA version is stuck in a commit from June 2021.

I'll try to figure out why, but in the meantime you can pull the latest version from github and it should work.

**Comment by karthink** [comment] 2021-09-12 00:26
The MELPA version appears to be updated to the latest commit now. Please test.

**Comment by brownts** [comment] 2021-09-12 15:41
Yes, I can confirm that was my issue.  I had installed from MELPA which was stuck on the June commit.  I pulled the latest and it does work in this scenario.  Thanks for looking into this!

**Comment by karthink** [comment] 2021-09-12 18:18
MELPA appears to have updated too, so I'm closing this issue. Feel free to continue the discussion on maximizing popups. If you have any ideas that involve not saving and restoring window configurations it will be helpful.

**Closed by karthink** 2021-09-12 18:18 UTC
